# Python basics

In this notebook, we will learn:
- simple Python syntax
- variables and data types
- lists
- conditions and loops
- functions

In [ ]:
# First Command
# https://docs.python.org/3/tutorial/introduction.html#text
print("Hello, notebook!")

Hello, notebook!


Read the datatype: https://docs.python.org/3/library/stdtypes.html

In [1]:
# Variables
name = "Progenetix"
year = 2026
print(name)
print(year)

Progenetix
2026

In [2]:
# Basic Data Type
text = "bioinformatics"
number = 10
decimal = 3.14
flag = True

print(type(text))
print(type(number))
print(type(decimal))
print(type(flag))

<class 'str'>
<class 'int'>
<class 'float'>
<class 'bool'>

In [ ]:
# Simple Calculation
# https://docs.python.org/3/tutorial/introduction.html#using-python-as-a-calculator

a = 5
b = 2

print(a + b)
print(a - b)
print(a * b)
print(a / b)

7
3
10
2.5

In [ ]:
# Lists
# https://docs.python.org/3/tutorial/introduction.html#lists
cancer_types = ["breast", "lung", "colon"]
print(cancer_types)
print(cancer_types[0])
print(len(cancer_types))

['breast', 'lung', 'colon']
breast
3

In [5]:
# Add to a list
cancer_types.append("brain")
print(cancer_types)

['breast', 'lung', 'colon', 'brain']

Control Flows: https://docs.python.org/3/tutorial/controlflow.html#if-statements

In [6]:
# IF-ELSE Statement
x = 3

if x > 5:
    print("x is greater than 5")
else:
    print("x is 5 or smaller")

x is 5 or smaller

In [7]:
# For Loop
for cancer in cancer_types:
    print(cancer)

breast
lung
colon
brain

In [ ]:
# Function
# https://docs.python.org/3/tutorial/controlflow.html#defining-functions

def greet(name):
    print("Hello,", name)

greet("students")

Hello, students

In [9]:
# Use package
import math

print(math.sqrt(16))

4.0

## Exercise

Try the following:

- create a variable called `sample_number`
- create a list with three gene names:
  - `TP53`
  - `EGFR`
  - `MYC`
- complete the `if` statement
- complete the function and use a `for` loop to print all gene names

In [ ]:
sample_number = 3
gene_names = ["TP53", "EGFR", "MYC"]

# fill in the condition
if sample_number > #____:
    print("More than two samples")
else:
    print("Two or fewer samples")


def print_genes(genes):
    # fill in the loop
    for gene in #______:
        print(gene)


print_genes(gene_names)

## Introduction to pandas and NumPy

Before working with real biological data, it is useful to learn two very common Python libraries:

- **pandas**: for working with tabular data (https://pandas.pydata.org/docs/)
- **NumPy**: for working with numbers and arrays (https://numpy.org/doc/)

These libraries are widely used in data analysis and will be helpful for the next notebook on Progenetix data.

In [10]:
# Import Pandas and Numpy
import pandas as pd
import numpy as np

A pandas DataFrame is a table with rows and columns.
It is one of the most common data structures in Python data analysis.

In [11]:
# Create a simple dataset and use pandas dataframe for it
data = {
    "sample_id": ["S1", "S2", "S3"],
    "cancer_type": ["breast", "lung", "colon"],
    "value": [2.3, 1.8, 3.1]
}

df = pd.DataFrame(data)
df

  sample_id cancer_type  value
0        S1      breast    2.3
1        S2        lung    1.8
2        S3       colon    3.1

Look at the dataset

In [12]:
df.head()

  sample_id cancer_type  value
0        S1      breast    2.3
1        S2        lung    1.8
2        S3       colon    3.1

In [13]:
df.shape

(3, 3)

In [14]:
df.columns

Index(['sample_id', 'cancer_type', 'value'], dtype='str')

In [15]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 3 entries, 0 to 2
Data columns (total 3 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   sample_id    3 non-null      str
 1   cancer_type  3 non-null      str
 2   value        3 non-null      float64
dtypes: float64(1), str(2)
memory usage: 204.0 bytes

In [16]:
# select one column
df["cancer_type"]

0    breast
1      lung
2     colon
Name: cancer_type, dtype: str

In [17]:
# select more than one column
df[["sample_id", "value"]]

  sample_id  value
0        S1    2.3
1        S2    1.8
2        S3    3.1

This command exports the DataFrame to a CSV file.
The option `index=False` means that the row index is not written to the file.

In [18]:
df.to_csv("example_dataset.csv", index=False)

Read the created dataset

In [19]:
df2 = pd.read_csv("example_dataset.csv")
df2

  sample_id cancer_type  value
0        S1      breast    2.3
1        S2        lung    1.8
2        S3       colon    3.1

# Simple Numpy Command

In [20]:
values = np.array([2.3, 1.8, 3.1])
values

array([2.3, 1.8, 3.1])

In [21]:
print("Mean:", np.mean(values))
print("Maximum:", np.max(values))
print("Minimum:", np.min(values))

Mean: 2.4
Maximum: 3.1
Minimum: 1.8

Create numbers with Numpy

In [22]:
np.arange(5)

array([0, 1, 2, 3, 4])

In [23]:
np.arange(1, 11, 2)

array([1, 3, 5, 7, 9])

## Exercise

Try the following:

- create a small DataFrame with three rows
- include the columns:
  - `sample_id`
  - `gene`
  - `value`
- export the DataFrame to a CSV file
- read the file again
- create a NumPy array with three numbers
- calculate the mean of the array